spring:
  application:
    name: AuthServer
  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://betgeek-database.cltysbwuh4vq.us-east-2.rds.amazonaws.com:3306/bebetting_bet_server
#    username: admin
#    password: betpassword
    platform: postgres
    url: jdbc:postgresql://surebet.cvwkv2akfq0s.eu-west-3.rds.amazonaws.com:5432/betgeek
    username: surebet
    password: qOkXhE8LImQIzN0p
  jpa:
    show-sql: true
  redis:
    cluster:
      nodes: redis-core-bot-0001-001.q4dbc2.0001.euw3.cache.amazonaws.com:6379, redis-core-bot-0001-002.q4dbc2.0001.euw3.cache.amazonaws.com:6379, redis-core-bot-0001-003.q4dbc2.0001.euw3.cache.amazonaws.com:6379
server:
  port: 9090
  ssl:
    key-alias: betgeek-cert
    key-store-type: JKS
    key-password: changeit
    key-store: classpath:betgeek-cert.jks
betgeek:
  passbolt:
    admin:
      fingerprint: 24F3D4CA2F65532C2246440CA53C33FBB01E252C 
      id: 8603e25c-f321-463e-8044-34bc23333d0c
      publicKey: public-passbolt@betgeek.io.asc
      privateKey: private-passbolt@betgeek.io.asc
      secret: BetGeekPassBoltM4inP44Sw0rd$.
  config:
    oauth2:
      userClientOauth2: auth-betgeek
      secretClientOauth2: 4u7hb37g33kp4ssw0rd
      symmetricKeyJwt: symmetr1cJWTs3cr37
  configuration:
    redis:
      type: nodes
